export const GET_ALL_PRODUCT_DATA = "GET_ALL_PRODUCT_DATA";
export const GET_SEARCH_PRODUCT = "GET_SEARCH_PRODUCT";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const UPDATE_SINGLE_PRODUCT = "UPDATE_SINGLE_PRODUCT";
export const DELETE_SINGLE_PRODUCT = "DELETE_SINGLE_PRODUCT";
export const GET_ORDER_ALL_DATA = "GET_ORDER_ALL_DATA";
export const GET_REGISTRATION_ALL_DATA = "GET_REGISTRATION_ALL_DATA";
export const DATE_FILTER_IN_ORDER = "DATE_FILTER_IN_ORDER";

